[package]
name = "torch_bigram"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
tch = {version="0.13.0", features=[]}
termcolor = "1.2.0"
