[package]
name = "mlp_bengio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
itertools = "0.10.5"
tch = "0.9.0"
termcolor = "1.1.3"
